# Define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

# Uncomment this line if you're using Swift
use_frameworks!

target 'AvatarCapture' do
  pod 'FontAwesome.swift'
end